### PR TITLE
Please check for changes!!

### LINKED ISSUE #13: improve the design for the front page

### PR DESCRIPTION
**Pull request by Codedude1**
__13__ 

Fixes #13 

#### Short description of what this resolves:
Changed the font sizes, button colors and border radius!!
Added Hover effects on navbar links!!

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by ujjwal-batra** [comment]
@Codedude1 live link??

**Comment by Codedude1** [comment]
https://codedude1.github.io/
@ujjwal-batra Sir, here is the live link!!!

**Comment by ujjwal-batra** [comment]
@Codedude1 resolve conflicts

**Comment by Codedude1** [comment]
@ujjwal-batra Sir, done.

**Comment by ujjwal-batra** [comment]
Screenshot (211)
Header items are repeated

**Pull request closed without merging**
