### PR TITLE
Added authentication via Google using Firebase

### LINKED ISSUE #50: Add authentication via Google using firebase

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__50__ 

Fixes #50

#### Short description of what this resolves:

Added authentication via Google using Firebase

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
@thenullterminator  please review

**Comment by untrulynoxiusmj** [comment]
@thenullterminator please review

**Comment by thenullterminator** [comment]
@untrulynoxiusmj test the authentication by signing in and share the ss of the auth console showing your name and sign in method.

**Comment by untrulynoxiusmj** [comment]
google

**Pull request merged**
