### PR TITLE
Added validation to Signup Page

### LINKED ISSUE #23: Add validation to sign up page
Make sure proper error messages are displayed.(using HTML only)

### PR DESCRIPTION
**Pull request by ananya-mohanty**
__23__

Fixes #23 

#### Short description of what this resolves:

Added validation using only HTML (as asked).
Screenshot 2020-01-21 at 10 32 24 PM

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by NitinMadhukar** [comment]
@ananya-mohanty  live link?

**Comment by ananya-mohanty** [comment]
Live Link : https://ananya-mohanty.github.io/Portal/

**Comment by ananya-mohanty** [comment]
Live Link : https://ananya-mohanty.github.io/Portal/

**Comment by NitinMadhukar** [comment]
@ananya-mohanty there are two home,courses and notes buttons . 
correct this

**Comment by ananya-mohanty** [comment]
Done! (Sorry, hadn't noticed that)

**Pull request merged**
