### PR TITLE
Please check for changes

### LINKED ISSUE #13: improve the design for the front page

### PR DESCRIPTION
**Pull request by Codedude1**
__13__ 

Fixes #13 

#### Short description of what this resolves:
Resized the SignUp and Contacts buttons

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Codedude1** [comment]
Live link : https://codedude1.github.io/

**Comment by NitinMadhukar** [comment]
resolve conflicts @Codedude1

**Comment by Codedude1** [comment]
@NitinMadhukar Done, Sir.

**Comment by NitinMadhukar** [comment]
> @NitinMadhukar Done, Sir.

you have to resize the buttons and don't remove the footer. Update your repo and then make changes accordingly.

**Pull request closed without merging**
