### PR TITLE
task completed

### LINKED ISSUE #1: Add a footer to the website

### PR DESCRIPTION
**Pull request by garvitchittora**
__1__ 

Fixes #1

#### Short description of what this resolves:
added footer .
https://garvitchittora.github.io/ 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by ujjwal-batra** [comment]
improve the design.... we dont need links to social media

**Comment by ujjwal-batra** [comment]
footer

**Comment by ujjwal-batra** [comment]
something like this

**Comment by ujjwal-batra** [comment]
@garvitchittora updates?

**Comment by garvitchittora** [comment]
ok sir , i will update it .

**Pull request closed without merging**
